import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Avatar } from '@mui/material'
import { makeStyles } from '@mui/styles'
import { VerticalTextSlider } from '../components/verticalTextSlider'
import { SocialNavigator } from '../components/socialNavigator'


export default function Home() {

	const staticText = 'Hi, I\'m Victor:';
	const dynamicTexts = [
		{ text: 'Software Engineer ', emoji: '💻' },
		{ text: 'Entrepreneur ', emoji: '🌱' },
		{ text: 'Technology lover', emoji: '❤️' },
	];
	const socialIcons = [
		'https://github.com/VictorGreco/',
		'https://twitter.com/VGTTech',
		'https://www.linkedin.com/in/victor-greco/',
		'https://medium.com/@victorgrecotech',
		'https://codepen.io/victorgreco',
		'mailto:victorgrecotech@gmail.com',
		'https://es.stackoverflow.com/users/269347/victor-greco-tortajada'
	]

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
  				rel="stylesheet"
  				href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;display=swap"
				/>
			</Head>

			<main className={styles.main}>
				<VerticalTextSlider 
					staticText={staticText}
					dynamicTexts={dynamicTexts}
					 />

				<Avatar 
					alt="Victor Greco" 
					src="/static/images/avatar.png"
					sx={{ width: 200, height: 200 }}
					></Avatar>

				<SocialNavigator
					socialIcons={socialIcons}
				/>
			</main>
		</div>
	)
}
